import type { Talent } from "./types";

export const DEMO_TALENTS: Talent[] = [
  {
    id: "demo-talent-1",
    created_at: new Date().toISOString(),
    name: "松丸志保",
    age: null,
    gender: null,
    role: "AD",
    company: null,
    bio: "リサーチ、ロケ、編集、収録準備、デスク業務経験。趣味は読書、韓国語学習。",
    experience_programs: [
      'NTV特番「国民一斉調査」（2024年4月〜7月）',
      'MBS「プレバト！！」（2024年8月〜10月）',
      'EX「ミラクル9」（2024年12月〜）',
    ],
    genres: ["バラエティ"],
    skills: ["リサーチ", "ロケ", "編集", "収録準備", "デスク業務"],
    specialties: ["読書", "韓国語学習"],
    qualifications: [],
    hashtags: ["AD", "バラエティ", "リサーチ", "ロケ", "編集", "デスク業務", "韓国語", "読書"],
    image_url: null,
    is_active: true,
  },
  {
    id: "demo-talent-2",
    created_at: new Date().toISOString(),
    name: "樋口舞冬",
    age: null,
    gender: null,
    role: "AD",
    company: "博報堂プロダクツ 動画コンテンツクリエイティブ事業本部",
    bio: "リサーチ、仕込み、ロケ、編集のAD業務全般。",
    experience_programs: ['EX「帰れマンデー見っけ隊!!」', "WOKASHI"],
    genres: ["バラエティ", "Web動画"],
    skills: ["リサーチ", "仕込み", "ロケ", "編集"],
    specialties: [],
    qualifications: ["普通自動車第一種運転免許"],
    hashtags: ["AD", "バラエティ", "ロケ", "編集", "仕込み", "リサーチ", "運転免許", "臨機応変"],
    image_url: null,
    is_active: true,
  },
];
